table fact_orders
	lineageTag: 9112d308-6c42-4ba4-8ab5-fcc3308ce21c

	column order_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3c5d22c4-51c9-4a70-afb2-33a808c877d3
		summarizeBy: sum
		sourceColumn: order_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column order_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7c573c0a-e6ec-4d1c-b76a-c713226d39d1
		summarizeBy: none
		sourceColumn: order_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column user_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 96e44f6a-008d-43f2-878e-492737eed746
		summarizeBy: none
		sourceColumn: user_id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column revenue
		dataType: double
		formatString: #,0.00
		lineageTag: f0ffd74d-748d-424d-84c7-3a4b1459bac1
		summarizeBy: sum
		sourceColumn: revenue

		annotation SummarizationSetBy = Automatic

	column flag_cancelled
		dataType: int64
		formatString: 0
		lineageTag: 776aa2d7-5bf8-4bd4-b6af-1a8f4d77877a
		summarizeBy: sum
		sourceColumn: flag_cancelled

		annotation SummarizationSetBy = Automatic

	partition fact_orders = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\gusta\OneDrive\Área de Trabalho\Cursos\projetos\revenue_dashboard\data\orders.xlsx"), null, true),
				    orders_Sheet = Fonte{[Item="orders",Kind="Sheet"]}[Data],
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(orders_Sheet, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"order_id", Int64.Type}, {"order_date", type date}, {"user_id", Int64.Type}, {"product_id", Int64.Type}, {"revenue", type number}}),
				    #"Colunas Renomeadas" = Table.RenameColumns(#"Tipo Alterado",{{"product_id", "item_id"}}),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Colunas Renomeadas",{"order_id", "order_date", "user_id", "revenue"}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Outras Colunas Removidas"),
				    #"Personalização Adicionada" = Table.AddColumn(#"Duplicatas Removidas", "flag_cancelled", each if [revenue] = 0 then 1 else 0),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Personalização Adicionada",{{"flag_cancelled", Int64.Type}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

